distrName = 'Hello, World!';
pipelineFolders = 'helloworld';
ref = 'heads';
ver = 'ywc-lite-genesis';
launcher = 'braph2helloworld';
rollcall = { ...
    '+util', '+_Exporter.gen.m', '+_Importer.gen.m', ...
    '+ds*', '-ds_examples', ...
    '-analysis', ...
    '+atlas*', '-_ExporterBrainAtlasTXT.gen', '-_ExporterBrainAtlasXLS.gen', '-_ImporterBrainAtlasTXT.gen', '-_ImporterBrainAtlasXLS.gen', ...
    '+gt*', ...
    '-cohort', ...
    '-nn', ...
    '+gui*', '-_PanelPropCell.gen.m', '-_PanelPropClassList.gen.m', '-_PanelPropRVectorSmart.gen.m', '-_PanelPropStringList.gen.m', ...
    '+brainsurfs', ...
    '+atlases', ...
    '-graphs', ...
    '-measures', ...
    '-neuralnetworks', ...
    '+pipelines', ...
        '+helloworld*', ...
    '+test*', ...
    '-sandbox' ...
    };
filesToDelete = { ...
    };