clear all

generate_readme(['braph2' filesep 'tut_braph2.tex'])

generate_readme(['data' filesep 'tut_ba' filesep 'tut_ba.tex'])
generate_readme(['data' filesep 'tut_gr_con' filesep 'tut_gr_con.tex'])
generate_readme(['data' filesep 'tut_gr_fun' filesep 'tut_gr_fun.tex'])
generate_readme(['data' filesep 'tut_gr_st' filesep 'tut_gr_st.tex'])
generate_readme(['data' filesep 'tut_gr_con_mp' filesep 'tut_gr_con_mp.tex'])
generate_readme(['data' filesep 'tut_gr_fun_mp' filesep 'tut_gr_fun_mp.tex'])
generate_readme(['data' filesep 'tut_gr_st_mp' filesep 'tut_gr_st_mp.tex'])
%generate_readme(['data' filesep 'tut_gr_con_fun_mp' filesep 'tut_gr_con_fun_mp.tex'])

generate_readme(['pipelines' filesep 'tut_a_con_but' filesep 'tut_a_con_but.tex'])
generate_readme(['pipelines' filesep 'tut_a_con_bud' filesep 'tut_a_con_bud.tex'])
generate_readme(['pipelines' filesep 'tut_a_con_wu' filesep 'tut_a_con_wu.tex'])
generate_readme(['pipelines' filesep 'tut_a_con_ga_wu' filesep 'tut_a_con_ga_wu.tex'])
generate_readme(['pipelines' filesep 'tut_a_fun_ga_wu' filesep 'tut_a_fun_ga_wu.tex'])
generate_readme(['pipelines' filesep 'tut_a_con_wd' filesep 'tut_a_con_wd.tex'])
generate_readme(['pipelines' filesep 'tut_a_fun_bud' filesep 'tut_a_fun_bud.tex'])
generate_readme(['pipelines' filesep 'tut_a_fun_but' filesep 'tut_a_fun_but.tex'])
generate_readme(['pipelines' filesep 'tut_a_fun_wu' filesep 'tut_a_fun_wu.tex'])
generate_readme(['pipelines' filesep 'tut_a_st_wu' filesep 'tut_a_st_wu.tex'])
generate_readme(['pipelines' filesep 'tut_a_st_bud' filesep 'tut_a_st_bud.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_con_fun_wu' filesep 'tut_a_mp_con_fun_wu.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_con_fun_bud' filesep 'tut_a_mp_con_fun_bud.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_con_fun_but' filesep 'tut_a_mp_con_fun_but.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_con_wu' filesep 'tut_a_mp_con_wu.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_fun_wu' filesep 'tut_a_mp_fun_wu.tex'])
generate_readme(['pipelines' filesep 'tut_a_omp_con_wu' filesep 'tut_a_omp_con_wu.tex'])
generate_readme(['pipelines' filesep 'tut_a_omp_ga_con_wu' filesep 'tut_a_omp_ga_con_wu.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_con_bud' filesep 'tut_a_mp_con_bud.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_con_but' filesep 'tut_a_mp_con_but.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_fun_bud' filesep 'tut_a_mp_fun_bud.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_fun_but' filesep 'tut_a_mp_fun_but.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_ga_con_wu' filesep 'tut_a_mp_ga_con_wu.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_ga_fun_wu' filesep 'tut_a_mp_ga_fun_wu.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_ga_con_fun_wu' filesep 'tut_a_mp_ga_con_fun_wu.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_ga_con_fun_bud' filesep 'tut_a_mp_ga_con_fun_bud.tex'])
generate_readme(['pipelines' filesep 'tut_a_mp_st_bud' filesep 'tut_a_mp_st_bud.tex'])
% generate_readme(['pipelines' filesep 'tut_nn_reg_st' filesep 'tut_nn_reg_st.tex'])
% generate_readme(['pipelines' filesep 'tut_nn_clas_con_bud_g' filesep 'tut_nn_clas_con_bud_g.tex'])
% generate_readme(['pipelines' filesep 'tut_nn_clas_con_wu' filesep 'tut_nn_clas_con_wu.tex'])
% generate_readme(['pipelines' filesep 'tut_nn_clas_fun_wu_xval' filesep 'tut_nn_clas_fun_wu_xval.tex'])
generate_readme(['pipelines' filesep 'tut_nn_clas_con_fun_mp_bud_m_xval' filesep 'tut_nn_clas_con_fun_mp_bud_m_xval.tex'])
generate_readme(['pipelines' filesep 'tut_nn_clas_con_fun_mp_but_m_xval' filesep 'tut_nn_clas_con_fun_mp_but_m_xval.tex'])
generate_readme(['pipelines' filesep 'tut_nn_clas_con_fun_mp_data_xval' filesep 'tut_nn_clas_con_fun_mp_data_xval.tex'])
generate_readme(['pipelines' filesep 'tut_nn_clas_con_fun_mp_wu_xval' filesep 'tut_nn_clas_con_fun_mp_wu_xval.tex'])
generate_readme(['pipelines' filesep 'tut_nn_clas_reg_fun_mp_but_xval' filesep 'tut_nn_clas_reg_fun_mp_but_xval.tex'])
generate_readme(['pipelines' filesep 'tut_nn_reg_con_fun_mp_bud_xval' filesep 'tut_nn_reg_con_fun_mp_bud_xval.tex'])
generate_readme(['pipelines' filesep 'tut_nn_reg_con_fun_mp_data_split' filesep 'tut_nn_reg_con_fun_mp_data_split.tex'])
generate_readme(['pipelines' filesep 'tut_nn_reg_con_fun_mp_wu_m_xval' filesep 'tut_nn_reg_con_fun_mp_wu_m_xval.tex'])

generate_readme(['pipelines' filesep 'tut_nn_clas_con_bud_m_xval' filesep 'tut_nn_clas_con_bud_m_xval.tex'])
generate_readme(['pipelines' filesep 'tut_nn_clas_con_bud_xval' filesep 'tut_nn_clas_con_bud_xval.tex'])
generate_readme(['pipelines' filesep 'tut_nn_clas_con_but_m_xval' filesep 'tut_nn_clas_con_but_m_xval.tex'])
generate_readme(['pipelines' filesep 'tut_nn_clas_con_data_split' filesep 'tut_nn_clas_con_data_split.tex'])
generate_readme(['pipelines' filesep 'tut_nn_clas_con_wu_xval' filesep 'tut_nn_clas_con_wu_xval.tex'])
generate_readme(['pipelines' filesep 'tut_nn_reg_con_wu_m_xval' filesep 'tut_nn_reg_con_wu_m_xval.tex'])
generate_readme(['pipelines' filesep 'tut_nn_reg_con_but_xval' filesep 'tut_nn_reg_con_but_xval.tex'])
generate_readme(['pipelines' filesep 'tut_nn_reg_con_data_split' filesep 'tut_nn_reg_con_data_split.tex'])

generate_readme(['developers' filesep 'dev_pipeline' filesep 'dev_pipeline.tex'])
generate_readme(['developers' filesep 'dev_script' filesep 'dev_script.tex'])
generate_readme(['developers' filesep 'dev_intro' filesep 'dev_intro.tex'])
generate_readme(['developers' filesep 'dev_graph' filesep 'dev_graph.tex'])
generate_readme(['developers' filesep 'dev_measure' filesep 'dev_measure.tex'])
generate_readme(['developers' filesep 'dev_subject' filesep 'dev_subject.tex'])
generate_readme(['developers' filesep 'dev_nn_datapoint' filesep 'dev_nn_datapoint.tex'])
generate_readme(['developers' filesep 'dev_nn_clas' filesep 'dev_nn_clas.tex'])
generate_readme(['developers' filesep 'dev_nn_reg' filesep 'dev_nn_reg.tex'])
generate_readme(['developers' filesep 'dev_nn_xval' filesep 'dev_nn_xval.tex'])
generate_readme(['developers' filesep 'dev_panelprop' filesep 'dev_panelprop.tex'])
generate_readme(['developers' filesep 'dev_panelfig' filesep 'dev_panelfig.tex'])
generate_readme(['developers' filesep 'dev_analysis_ensemble' filesep 'dev_analysis_ensemble.tex'])
generate_readme(['developers' filesep 'dev_analysis_group' filesep 'dev_analysis_group.tex'])